### ISSUE TITLE
Test changes for another refactor on XRDP tasks

### ISSUE THREAD

**Issue by SystemFiles** [SystemFiles/ansible-xrdp-ubuntu#5]
Suggested changes (to be tested):

```yml
- name: XRDP | 9.0 | Patch Polkit
  block:
    - name: XRDP | 9.1 | Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    
    - name: XRDP | 9.2 | Check whether PolKit is installed on the system yet
      ansible.builtin.set_fact:
        pk_installed: true
      when: "'libpolkit-agent-1-0' in ansible_facts.packages"

    - name: XRDP | 9.3 | Gather PolKit version for patch params
      ansible.builtin.shell: pkaction --version | rev | cut -d' ' -f1 | rev
      changed_when: false
      register: pk_version
      when: xrdp.colord_bypass and pk_installed

    - name: XRDP | 9.4 | Ensure that colord patch is applied to the system - 'PolKit v0.106-'
      ansible.builtin.template:
        src: 45-allow-colord.j2
        dest: /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla
        group: root
        owner: root
        mode: 0751
      when: xrdp.colord_bypass and pk_installed and pk_version.stdout is version('0.106', '<')

    - name: XRDP | 9.5 | Ensure that colord patch is applied to the system - 'PolKit v0.106+'
      ansible.builtin.template:
        src: 45-allow-colord.j2
        dest: /etc/polkit-1/localauthority/50-local.d/45-allow-colord.conf
        group: root
        owner: root
        mode: 0751
      when: xrdp.colord_bypass and pk_installed and pk_version.stdout is version('0.106', '>=')
```
